######################################################################
# Automatically generated by qmake (2.01a) qui jun 21 12:51:45 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dmsa.h mainwindow.h pessoa.h
FORMS += mainwindow.ui
SOURCES += dmsa.cpp main.cpp mainwindow.cpp pessoa.cpp

OTHER_FILES += \
    notes.txt
